---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: users-pod
  template:
    metadata:
      labels:
        name: users-pod
    spec:
      containers:
      - name: users
        image: microservice_demo_users
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    name: users-service
spec:
  type: NodePort
  # externalTrafficPolicy: Local
  selector:
    name: users-pod
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
