---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    chart: {{ .Release.Name }}
    name: {{ .Release.Name }}-deployment
  annotations:
    # Following forces helm to update resource
    date/deploy-date: {{ now | quote }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-pod
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-pod
      annotations:
        # Following forces helm to update resource
        date/deploy-date: {{ now | quote }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.containerPort }}
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 1
          httpGet:
            path: /health
            port: {{ .Values.service.containerPort }}
      - name: sensu-agent
        image: sensu/sensu:latest
        command: ["/opt/sensu/bin/sensu-agent", "start", "--log-level=debug"]
        env:
        - name: SENSU_BACKEND_URL
          value: ws://sensu-backend.sensu-system.svc.cluster.local:8081
        - name: SENSU_NAMESPACE
          value: default
        - name: SENSU_SUBSCRIPTIONS
          value: pods
        - name: SENSU_DEREGISTER
          value: "true"
        - name: SENSU_STATSD_EVENT_HANDLERS
          value: statsd
