---
replicas: 2

image:
  name: k776/users-service
  tag: "0.0.1"

service:
  containerPort: 8080
  servicePort: 80

keel:
  policy: minor
  trigger: poll
  pollSchedule: "@every 1m"
  images:
    - repository: image.name
      tag: image.tag
