---
replicas: 2

image:
  name: k776/accounts-service
  tag: latest

service:
  containerPort: 8080
  servicePort: 80

keel:
  policy: force
  trigger: poll
  pollSchedule: "@every 1m"
  images:
    - repository: image.name
      tag: image.tag
