---
replicas: 1

image:
  name: k776/accounts-service
  tag: latest

service:
  containerPort: 8080
  servicePort: 80

autoscaler:
  minReplicas: 1
  maxReplicas: 10

keel:
  policy: force
  trigger: poll
  pollSchedule: "@every 1m"
  images:
    - repository: image.name
      tag: image.tag
