---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: users-service
spec:
  selector:
    matchLabels:
      name: users-service
  template:
    metadata:
      labels:
        name: users-service
    spec:
      containers:
        - name: users-service
          image: microservice_demo_users
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    name: users-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: users-service
spec:
  backend:
    serviceName: users-service
    servicePort: 80
